Rederived UHF and L-band model products
ska-sa/katsdpcal pull request #37
Opened 2020-09-17 09:35 UTC by bennahugo

As discussed via email the previous attempt to integrate off-axis model introduced astrometrical errors. To this end I have rederived subsets. I have carefully checked that these SP models subtracts out the primary calibrator and some of the brightest flux in the field after accounting for smeared response.

The UHF components are selected from across the field at 600MHz (where the phase errors are worst). The middle plot is truncated to the 75th quartile and includes the primary calibrator collapsed to a single component
![image](https://user-images.githubusercontent.com/7934586/93451084-02fccb00-f8d7-11ea-8891-4fa426cc44bc.png)

The 90 component model quotients with hand-calibrated data performs substantially better in phase than using a single component:
![image](https://user-images.githubusercontent.com/7934586/93451370-64bd3500-f8d7-11ea-93e6-516234dd2e9d.png)
vs. a single component model:
![image](https://user-images.githubusercontent.com/7934586/93451488-89191180-f8d7-11ea-8a46-39a02f950e11.png)

The residual amplitude skewness is only corrected once a vastly more detailed model is used
![image](https://user-images.githubusercontent.com/7934586/93451599-acdc5780-f8d7-11ea-9ead-17ca402ce1f7.png)

I've done the same for L-band although for B1934 there is essentially no problem at L-band, because the primary is substantially brighter and the beam modulated off-axis AGN population is substantially fainter
![image](https://user-images.githubusercontent.com/7934586/93451865-fe84e200-f8d7-11ea-8eee-3c0ee3618de7.png)

I have carefully checked that the flux scale of the primary source is contiguous in the usable part of the bandwidth
![image](https://user-images.githubusercontent.com/7934586/93453068-7dc6e580-f8d9-11ea-9343-57b2daffc68f.png)

2020-09-17 09:39 UTC, bennahugo commented
The same has to be done for B0407, however I have no calibrated products to test against, so this will need to go onto the backburner for now. I suggest that until that can be carefully tested we use a single delta component for that field.

2020-09-17 09:59 UTC, bennahugo commented
Please also note that these models are only valid for the current 64 dish homogeneous layout across the bandwidth that I indicated. Even the central component starts breaking down at the band rolloff
![image](https://user-images.githubusercontent.com/7934586/93455831-288cd300-f8dd-11ea-80cf-2b1887fe53ee.png)

2020-09-18 09:50 UTC, bennahugo commented
@KimMcAlpine can you please review these changes. I will check and fix 0407 in another PR. It will take a bit more time.

2020-09-18 10:03 UTC, KimMcAlpine requested changes

2020-09-18 10:03 UTC, KimMcAlpine commented on katsdpcal/conf/sky_models/J1939-6342_L.txt
> +prim, radec, 19:39:25.02671, -63:42:45.6255, 544 1088 wsclean 15.08878461 [-1.32055307 -7.71570958 15.0796986 -23.35984842 -29.32355766] False 1283791015.625
This is L-band model but all the components have flux limits 544 to 1088, should change these to the L-band limits

2020-09-18 10:03 UTC, KimMcAlpine commented on katsdpcal/conf/sky_models/J1939-6342_L.txt
> +s0c1846, radec, 19:37:20.195, -63:37:11.014, 544 1088 wsclean 0.0005499136584405929 [-0.00220578013815432 0.0185947344627738 -0.0509646389731988 0.0 0.0] False 1283791015.625
If adding these components makes a very limited different at L-band why have we upgraded the number of components from 50 to 90 ?

2020-09-18 10:04 UTC, bennahugo commented on katsdpcal/conf/sky_models/J1939-6342_L.txt
> +prim, radec, 19:39:25.02671, -63:42:45.6255, 544 1088 wsclean 15.08878461 [-1.32055307 -7.71570958 15.0796986 -23.35984842 -29.32355766] False 1283791015.625
Oh is that what those numbers are for? Ok will do

2020-09-18 10:05 UTC, bennahugo commented on katsdpcal/conf/sky_models/J1939-6342_L.txt
> +s0c1846, radec, 19:37:20.195, -63:37:11.014, 544 1088 wsclean 0.0005499136584405929 [-0.00220578013815432 0.0185947344627738 -0.0509646389731988 0.0 0.0] False 1283791015.625
I thought I keep them the same. Technically we do not need a model for L-band. Should we instead just have the central component?

2020-09-18 10:10 UTC, bennahugo commented
Done changed to the usable L-band bandwidth

2020-09-18 10:11 UTC, KimMcAlpine commented on katsdpcal/conf/sky_models/J1939-6342_L.txt
> +s0c1846, radec, 19:37:20.195, -63:37:11.014, 544 1088 wsclean 0.0005499136584405929 [-0.00220578013815432 0.0185947344627738 -0.0509646389731988 0.0 0.0] False 1283791015.625
Yes, I would be in favour of that

2020-09-18 15:39 UTC, bennahugo commented
Ok I've also redone B0407. The spread here is slightly bigger because I have done a very basic calibration of the field to check that subtracts. The previous model also had astrometry which was slightly off. The phase spread also reduced with this model:
![image](https://user-images.githubusercontent.com/7934586/93617089-d11e5e00-f9d5-11ea-8893-8fd8f91de538.png)

2020-09-18 15:40 UTC, bennahugo commented
(just for UHF for now. I still need to recalibrate some L-band data to check the L-band model. However it is not as important as getting the UHF system going).

2020-09-21 08:25 UTC, KimMcAlpine requested changes
A few minor comments

2020-09-21 08:25 UTC, KimMcAlpine commented on katsdpcal/conf/sky_models/J0408-6545_UHF.txt
> +# Fluxes and positions from B.Hugo model in Modelling of PKS B1934-638 (J193925.0-634245) as UHF and L-Band calibrator for MeerKAT
This comment mentions 1934-634, but this is 0408 ? Should you maybe change the comment ?

2020-09-21 08:25 UTC, KimMcAlpine commented on katsdpcal/conf/sky_models/J1939-6342_L.txt
> +prim, radec, 19:39:25.02671, -63:42:45.6255, 900 1650 wsclean 15.08878461 [-1.32055307 -7.71570958 15.0796986 -23.35984842 -29.32355766] False 1283791015.625
The valid frequency range has to cover the whole band of the observation, otherwise the cal pipeline won't use it at all. Even worse in the 32K split cal case is might use the model for the bandpass solution for the two inner parts of the band and not for the two outer parts, giving a completely non-continguous bandpass solution.

2020-09-22 11:47 UTC, KimMcAlpine approved these changes

2020-09-22 13:27 UTC, merged