Support multi-frequency setups for S-band
ska-sa/katsdpcal pull request #40
Opened 2020-12-18 09:35 UTC by KimMcAlpine

This is to address https://skaafrica.atlassian.net/browse/SPR1-463.
The cal pipeline uses a narrow range of frequencies (specified by e.g.
g_bfreq, g_efreq) to perform gain and delay calibration. These have
always been provided as a single float per band. S-band has multiple (5)
possible frequency setups across the full 1750 - 3500 MHz band, and a
single frequency range cannot be used for all 5 possible bands.

This modifies the pipeline to allow these parameters to be supplied as
either a list of a float. If a list is provided another parameter
('band_start_freq') is required, which provides a list of starting
 frequencies that correspond to the list of gain and delay calibration windows.

2021-01-11 12:17 UTC, ludwigschwardt requested changes

2021-01-11 12:17 UTC, ludwigschwardt commented on katsdpcal/pipelineprocs.py
> +                    parameters['band_start_freq']
You can remove this line, since the same code on the next line will trigger the `KeyError`.

2021-01-11 12:17 UTC, ludwigschwardt commented on katsdpcal/pipelineprocs.py
> +            if type(parameters[key]) == list:
Maybe do `if len(parameters[key]) > 1` instead, and cast the single-element list to a float in this function too.

2021-01-11 12:17 UTC, ludwigschwardt commented on katsdpcal/pipelineprocs.py
> +            return type_(parts[0])
This is now more like a `float_or_comma_list`... Maybe it is safer to postpone the list->float conversion to `parameters_for_freq`.

2021-01-11 12:17 UTC, ludwigschwardt commented on katsdpcal/pipelineprocs.py
> +    Parameter('k_bfreq', 'start frequency for k fit per band, (MHz)', comma_list(float)),
The term `band` is quite overloaded... You already have a config file per "band". Maybe call these `subbands`? Maybe there is a better SE-approved term for the S-band windows...

2021-01-11 12:17 UTC, ludwigschwardt commented on katsdpcal/conf/pipeline_params/pipeline_parameters_meerkat_S.txt
> +k_bfreq : 2010.60, 2517.60, 2876.46  # start frequency of first channel for K fit, MHz
"per band/subband/whatever", as advertised [here](https://github.com/ska-sa/katsdpcal/pull/40/files#diff-7fa31003c0f3d46c2a9e46af4aeab78251488f33d7cff8294c3fd88631c02633R145).

2021-01-12 13:58 UTC, KimMcAlpine commented on katsdpcal/conf/pipeline_params/pipeline_parameters_meerkat_S.txt
> +band_start_freq : 1750.00, 1968.75, 2406.25     #start frequency range for per band parameters
Done

2021-01-12 13:58 UTC, KimMcAlpine commented on katsdpcal/pipelineprocs.py
> +                    parameters['band_start_freq']
Removed

2021-01-12 14:10 UTC, KimMcAlpine commented on katsdpcal/pipelineprocs.py
> +            if type(parameters[key]) == list:
Changed as suggested

2021-01-12 14:10 UTC, KimMcAlpine commented on katsdpcal/pipelineprocs.py
> +            return type_(parts[0])
Done

2021-01-12 14:28 UTC, KimMcAlpine commented on katsdpcal/pipelineprocs.py
> +    Parameter('k_bfreq', 'start frequency for k fit per band, (MHz)', comma_list(float)),
I struggled a bit with how to describe these frequency slices/windows. I was a bit wary of subband because in several places in the comments the term sub-band is used to refer to the UHF, L, S distinction.
 I've changed it to `subband` for now but what do you think about `subband window` ? 
If there is a SE-approved term where would I find it ?

2021-01-12 14:28 UTC, KimMcAlpine commented on katsdpcal/conf/pipeline_params/pipeline_parameters_meerkat_S.txt
> +k_bfreq : 2010.60, 2517.60, 2876.46  # start frequency of first channel for K fit, MHz
Changed to per `subband`

2021-01-13 13:28 UTC, ludwigschwardt commented on katsdpcal/pipelineprocs.py
> +    Parameter('k_bfreq', 'start frequency for k fit per band, (MHz)', comma_list(float)),
I was very worried by your statement about subband referring to L / S / UHF (consistent naming is my bugbear!), until it dawned on me a second ago... That's probably the `sub_band` CAM sensor, with `sub` referring to the `subarray` component - i.e. the band at the subarray level 🤣 🤣

I'll poll the SEs for more wisdom.

2021-01-13 14:04 UTC, KimMcAlpine commented
Indeed it is the `sub_band` CAM sensor :)

On Wed, Jan 13, 2021 at 3:28 PM Ludwig Schwardt <notifications@github.com>
wrote:

> *@ludwigschwardt* commented on this pull request.
> ------------------------------
>
> In katsdpcal/pipelineprocs.py
> <https://github.com/ska-sa/katsdpcal/pull/40#discussion_r556518507>:
>
> > @@ -140,10 +142,12 @@ def convert(value):
>
>
>
>  # Parameters that the user can set directly, in units of Hz/MHz
>
>  USER_PARAMS_FREQS = [
>
> -    Parameter('k_bfreq', 'start frequency for k fit, (MHz)', float),
>
> -    Parameter('k_efreq', 'stop frequency for k fit, (MHz)', float),
>
> -    Parameter('g_bfreq', 'start frequency for g fit, (MHz)', float),
>
> -    Parameter('g_efreq', 'stop frequency for g fit, (MHz)', float),
>
> +    Parameter('k_bfreq', 'start frequency for k fit per band, (MHz)', comma_list(float)),
>
>
> I was very worried by your statement about subband referring to L / S /
> UHF (consistent naming is my bugbear!), until it dawned on me a second
> ago... That's probably the sub_band CAM sensor, with sub referring to the
> subarray component - i.e. the band at the subarray level 🤣 🤣
>
> I'll poll the SEs for more wisdom.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ska-sa/katsdpcal/pull/40#discussion_r556518507>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACMD2WLWNLDPRTA7HRZUHNLSZWNY3ANCNFSM4VA5KURQ>
> .
>

2021-01-14 14:06 UTC, ludwigschwardt commented on katsdpcal/pipelineprocs.py
> +            elif len(parameters[key]) == 1:
I guess if `len(parameters[key]) < 1` all hell will break loose 😆

2021-01-14 14:07 UTC, ludwigschwardt commented on katsdpcal/pipelineprocs.py
>                      band_idx = max([i for i, s_freq in enumerate(parameters['band_start_freq'])
I would change this to `subband_idx` for clarity.

2021-01-14 14:09 UTC, ludwigschwardt commented on katsdpcal/pipelineprocs.py
>      Parameter('band_start_freq', 'start frequency range corresponding to parameters'
I would change this to `subband_start_freq` for clarity (or even `subband_bfreq` to match the others 😆 )

2021-01-14 14:18 UTC, ludwigschwardt commented on katsdpcal/pipelineprocs.py
> +    Parameter('k_bfreq', 'start frequency for k fit per band, (MHz)', comma_list(float)),
The SE hasn't come back to me yet, so I think this is OK for now.

2021-01-14 14:19 UTC, ludwigschwardt requested changes
Nearly there!

2021-01-18 12:05 UTC, KimMcAlpine commented on katsdpcal/pipelineprocs.py
>                      band_idx = max([i for i, s_freq in enumerate(parameters['band_start_freq'])
Done

2021-01-18 13:00 UTC, KimMcAlpine commented on katsdpcal/pipelineprocs.py
>      Parameter('band_start_freq', 'start frequency range corresponding to parameters'
changed to `subband_bfreq`

2021-01-18 13:03 UTC, KimMcAlpine commented on katsdpcal/pipelineprocs.py
> +            elif len(parameters[key]) == 1:
Hmm, this reminded me that in theory a user can supply  e.g. `g_bchan` directly in units of channels, in which case the `g_bfreq` key could be entirely absent or an empty list, so I've modified this to hopefully cope with this a bit more gracefully.

2021-01-18 13:10 UTC, ludwigschwardt commented on katsdpcal/pipelineprocs.py
> +    subband_keys = ['g_bfreq', 'g_efreq', 'k_bfreq', 'k_efreq']
A good idea, otherwise `subband_bfreq` is also picked up :-D

2021-01-18 13:12 UTC, ludwigschwardt approved these changes
A very slight niggle and a very slight question...

2021-01-18 13:12 UTC, ludwigschwardt commented on katsdpcal/pipelineprocs.py
> +            elif len(parameters[key]) == 1:
I'm not sure which modifications you refer to...

2021-01-18 13:21 UTC, KimMcAlpine commented
At the top (line 434) I've added the check `if key in parameters and
parameters[key] != []`, so this should guard against the possibility that
the length of the list is `<1`


On Mon, Jan 18, 2021 at 3:12 PM Ludwig Schwardt <notifications@github.com>
wrote:

> *@ludwigschwardt* approved this pull request.
>
> A very slight niggle and a very slight question...
> ------------------------------
>
> In katsdpcal/pipelineprocs.py
> <https://github.com/ska-sa/katsdpcal/pull/40#discussion_r559556813>:
>
> >                      band_idx = max([i for i, s_freq in enumerate(parameters['band_start_freq'])
>                                      if min(channel_freqs/1e6) >= s_freq])
>                      parameters[key] = parameters[key][band_idx]
>                  except KeyError:
>                      logger.error("If '%s' is a list of values,"
>                                   " a 'band_start_freq' parameter is required", key)
>                      raise
> +            elif len(parameters[key]) == 1:
>
> I'm not sure which modifications you refer to...
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ska-sa/katsdpcal/pull/40#pullrequestreview-570476528>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACMD2WI7BVZB4RZVIKUM4DLS2QXTNANCNFSM4VA5KURQ>
> .
>

2021-01-18 13:35 UTC, ludwigschwardt commented on katsdpcal/pipelineprocs.py
> +        if key in parameters and parameters[key] != []:
Ah, right!

A small suggestion here (not a showstopper, so only do if you feel like it):

You could replace this line with
```Python
if key not in parameters:
    continue
```
- This reduces the indentation and restores the Happy Path™.
- It also avoids comparison with an empty list, which seems less appropriate than `len(x) > 0` or simply `if x`, which would work on any sequence.

2021-01-18 14:02 UTC, KimMcAlpine commented on katsdpcal/pipelineprocs.py
> +        if key in parameters and parameters[key] != []:
Done, the Happy Path has been restored :)

2021-01-18 14:04 UTC, ludwigschwardt approved these changes
Yay, happy!

2021-01-18 15:21 UTC, merged