Narrowband cal
ska-sa/katsdpcal pull request #50
Opened 2021-06-30 14:53 UTC by KimMcAlpine

Modify the pipeline to select appropriate parameters for narrowband observations.
This is to address the issues in [https://skaafrica.atlassian.net/browse/SPR1-1058](https://skaafrica.atlassian.net/browse/SPR1-1058).

2021-07-05 15:20 UTC, ludwigschwardt requested changes

2021-07-05 15:20 UTC, ludwigschwardt commented on katsdpcal/pipelineprocs.py
> +        actual_width = (channel_freqs[echan] - channel_freqs[bchan]) / 1e6
Now that you have already imported `astropy.units`, maybe it is a good idea to use it here as well.

2021-07-05 15:20 UTC, ludwigschwardt commented on katsdpcal/pipelineprocs.py
> +        for key in [p + '_bfreq']:
This for-loop looks like it will only ever do one thing...

2021-07-05 15:20 UTC, ludwigschwardt commented on katsdpcal/pipelineprocs.py
> +        max_chans_per_server = len(channel_freqs) // servers
This looks like the same value as before...

2021-07-05 15:20 UTC, ludwigschwardt commented on katsdpcal/pipelineprocs.py
> +def parameters_for_blank_sol(parameters, channel_freqs, static_mask, prefix):
`blank_sol` is a slightly unappealing name, but I don't have a catchy alternative :joy: `blank_freqwin`? `blank_freq_window`? `blank_befreq`? Something that suggests it is in the frequency domain seems like a good idea, but I don't know what.

2021-07-05 15:20 UTC, ludwigschwardt commented on katsdpcal/test/test_pipelineprocs.py
> +        self.mask = np.zeros([32768], dtype=bool)
No need for the square brackets.

2021-07-05 15:20 UTC, ludwigschwardt commented on katsdpcal/test/test_pipelineprocs.py
> +        self.mask[8192: 10092] = True
Extra whitespace after :

2021-07-05 15:20 UTC, ludwigschwardt commented on katsdpcal/test/test_pipelineprocs.py
> +        mask = np.zeros([4096], dtype=bool)
No need for the square brackets.

2021-07-05 15:20 UTC, ludwigschwardt commented on katsdpcal/test/test_pipelineprocs.py
> +            self.assertEqual(0, parameters['k_bchan'])
Wouldn't you expect the window to be 1024..2047? That `mask[500] = True` seems to fall in the middle of the selected solution interval.

2021-07-05 16:16 UTC, ludwigschwardt commented on katsdpcal/pipelineprocs.py
> +    """ Partition index into list of arrays of consecutive indices """
Looking for an alternative I've also just discovered `np.flatnonzero` 🎉

2021-07-06 12:15 UTC, KimMcAlpine commented on katsdpcal/conf/pipeline_params/pipeline_parameters_meerkat_L_narrow.txt
> +rfi_calib_spike_width_hz : 4179687   # 1sigma frequency width of smoothing Gaussian on calibrators, Hz
I discussed the parameter values a bit with Tom Mauch (as he is the original RFI flagger expert) and I tried to capture the relevant parts of these discussions in the narrowband Jira ticket (see [https://skaafrica.atlassian.net/browse/SPR1-1058](https://skaafrica.atlassian.net/browse/SPR1-1058))

He suggested that the smaller value for the calibrator in wideband `rfi_calib_spike_width_hz` was designed to match the higher variability in the bandpass at the lower end of L-band and that for narrowband (which is mostly tuned to the higher frequencies in L-band) a wider setting might be better because less local variation (which is presumably) RFI gets folded into the background estimate.

2021-07-06 12:23 UTC, KimMcAlpine commented on katsdpcal/conf/pipeline_params/pipeline_parameters_meerkat_S_narrow.txt
> +rfi_calib_spike_width_hz : 42727460  # 1sigma frequency width of smoothing Gaussian on calibrators, Hz
Oh no :(, I've set it to be the same as the `targ_spike_width_hz` value, as is the case for the other narrowband files

2021-07-06 12:27 UTC, KimMcAlpine commented on scripts/run_cal.py
> -        param_filename = 'pipeline_parameters_meerkat_{}.txt'.format(band)
Done

2021-07-06 12:56 UTC, KimMcAlpine commented on katsdpcal/pipelineprocs.py
> +        cbf = telstate_l0.join(instrument, 'antenna', 'channelised', 'voltage')
Excellent, have altered as per katdal

2021-07-06 14:11 UTC, KimMcAlpine commented on katsdpcal/simulator.py
> +        instrument = stream.split(self.file.source.telstate.SEPARATOR)[0]
Done

2021-07-06 14:16 UTC, KimMcAlpine commented on katsdpcal/pipelineprocs.py
> +    lengths, optional : float
Changed to a scalar, and modified to `length` in the documentation.

2021-07-06 14:16 UTC, KimMcAlpine commented on katsdpcal/pipelineprocs.py
> +        lengths = np.array([length])
Changed to a scalar

2021-07-06 14:18 UTC, KimMcAlpine commented on katsdpcal/pipelineprocs.py
> +            logger.warning('Failed to load rfi_mask model: s', exc)
changed to %s

2021-07-06 14:18 UTC, KimMcAlpine commented on katsdpcal/pipelineprocs.py
> +            logger.warning('Failed to load band_mask model: s', exc)
changed to %s

2021-07-06 14:24 UTC, KimMcAlpine commented on katsdpcal/pipelineprocs.py
> +    channel_width = channel_freqs[1] - channel_freqs[0]
Done

2021-07-07 07:52 UTC, KimMcAlpine commented on katsdpcal/pipelineprocs.py
> +    """Select appropriate solutions parameters for for the given solution types.
I've tried to improve the description in the summary line

2021-07-07 08:08 UTC, KimMcAlpine commented on katsdpcal/pipelineprocs.py
> +                chan_window = window
Done

2021-07-07 08:54 UTC, KimMcAlpine commented on katsdpcal/pipelineprocs.py
> +    default_chan_width = min(6400, max_chans_per_server)
I've modified the parameter from `default_chan_width` to `default_chan_count`, another option is `default_no_chans`, to improve clarity,

I've also modified the comment to hopefully clarify the selection of 6400 channels.

2021-07-07 08:55 UTC, KimMcAlpine commented on katsdpcal/pipelineprocs.py
> +        max_chans_per_server = len(channel_freqs) // servers
Yes, a bit of a gremlin :(, I've deleted this line its unnecessary

2021-07-07 09:29 UTC, KimMcAlpine commented on katsdpcal/pipelineprocs.py
> +def parameters_for_blank_sol(parameters, channel_freqs, static_mask, prefix):
It is a bit tricky, I've settled on `blank_freqwin` for now

2021-07-07 09:53 UTC, KimMcAlpine commented on katsdpcal/test/test_pipelineprocs.py
> +        self.mask = np.zeros([32768], dtype=bool)
removed

2021-07-07 09:53 UTC, KimMcAlpine commented on katsdpcal/test/test_pipelineprocs.py
> +        mask = np.zeros([4096], dtype=bool)
removed

2021-07-07 09:53 UTC, KimMcAlpine commented on katsdpcal/test/test_pipelineprocs.py
> +        self.mask[8192: 10092] = True
removed

2021-07-07 10:01 UTC, KimMcAlpine commented on katsdpcal/test/test_pipelineprocs.py
> +            self.assertEqual(0, parameters['k_bchan'])
Yes, but recall that after `finalise_parameters` is run the `k_bchan` and `k_echan` channel numbers are relative to the channels processed by the given server.
 So in this instance `1024` in absolute channel number is transformed to `0` for the second server in the 4 server sequence. The final `1` in `pipelineprocs.finalise_parameters(self.parameters, self.telstate_l0, 4, 1)` indicates that these parameters are for this second server.

2021-07-07 10:06 UTC, KimMcAlpine commented on katsdpcal/pipelineprocs.py
> +        for key in [p + '_bfreq']:
Hmm, maybe its a midweek slump for me but I'm not sure what you mean here. 
The intention here is to accomodate the possibility of only one pair of the `k` or `g` parameters being left blank , in this case prefix will equal either ['k'] or ['g'] and only one pair of parameters will be set, but in general use prefix will equal ['k', 'g'] and both pairs of parameters will be set.

2021-07-08 09:19 UTC, ludwigschwardt commented on katsdpcal/conf/pipeline_params/pipeline_parameters_meerkat_L_narrow.txt
> +rfi_calib_spike_width_hz : 4179687   # 1sigma frequency width of smoothing Gaussian on calibrators, Hz
Great! I should have read the ticket first - very nice write-up!

2021-07-08 09:25 UTC, ludwigschwardt commented on katsdpcal/pipelineprocs.py
> +        for key in [p + '_bfreq']:
I'm referring to `for key in [p + '_bfreq']:`. If `p = 'k'`, this will read `for key in ['k_bfreq']:`, which is only one thing. The same goes for `p = 'g'`. Rather just go:
```Python
for p in prefix:
        parameters[p + '_bfreq'] = [channel_freqs[bchan] / 1e6]
        parameters[p + '_efreq'] = [channel_freqs[echan] / 1e6]
```

2021-07-08 09:29 UTC, KimMcAlpine commented on katsdpcal/pipelineprocs.py
> +        actual_width = (channel_freqs[echan] - channel_freqs[bchan]) / 1e6
I've incorporated `astropy.units` here and other places I thought it might be useful

2021-07-08 09:40 UTC, KimMcAlpine commented on katsdpcal/pipelineprocs.py
> +        for key in [p + '_bfreq']:
Ah I see, sorry there are obviously some cobwebs in the grey matter :)

2021-07-08 12:27 UTC, ludwigschwardt requested changes
Cool!

2021-07-08 12:27 UTC, ludwigschwardt commented on katsdpcal/pipelineprocs.py
> +                       " than the default (%.3f MHz)", actual_sol_bandwidth.value,
This is unfortunate :-)

```Python
print('%.3f' % (1.2345 * u.Hz,))  # TypeError
print('{:.3f}'.format(1.2345 * u.Hz))  # 1.234 Hz
```
So the logger version doesn't work, otherwise you could have just passed the quantity straight to the logger.

2021-07-08 12:27 UTC, ludwigschwardt commented on katsdpcal/pipelineprocs.py
> +                bfreq_hz = parameters[freq] * 1e6 * u.Hz
`* u.MHz` :-) You can search MHz frequencies in a Hz array.

2021-07-08 12:27 UTC, ludwigschwardt commented on katsdpcal/test/test_pipelineprocs.py
> +        self.assertEqual(self.freqs[10092].to(u.MHz).value, parameters['k_bfreq'])
You can also multiply the righthand side with `u.MHz` instead of extracting the value of the lefthand side.

2021-07-08 12:27 UTC, ludwigschwardt commented on katsdpcal/simulator.py
> +        correlator_stream = telstate.view('sdp_l0')['src_streams'][0]
The `sdp_l0` stream is implicit in the katdal telstate view when you open the file, but explicit is also good :-)

2021-07-08 12:27 UTC, ludwigschwardt commented on katsdpcal/pipelineprocs.py
> +                                   if min(channel_freqs).to(u.MHz).value >= s_freq])
Rather multiply `s_freq` with `u.MHz`.

2021-07-08 12:27 UTC, ludwigschwardt commented on katsdpcal/pipelineprocs.py
> +    default_chan_count = min(6400, max_chans_per_server)
I had another idea: `default_width_chans`. It just `chan_width` that triggers the wrong idea for me.

2021-07-08 13:33 UTC, KimMcAlpine commented on katsdpcal/pipelineprocs.py
> +        f_engine_stream = telstate_l0.view(correlator_stream)['src_streams'][0]
I've added the `exclusive=True` here, to be safe ;)

2021-07-08 13:33 UTC, KimMcAlpine commented on katsdpcal/pipelineprocs.py
> +        static_mask = rfi_mask.is_masked(channel_freqs[np.newaxis, :],
Done

2021-07-08 13:33 UTC, KimMcAlpine commented on katsdpcal/pipelineprocs.py
>      return static_mask[0]
Done

2021-07-08 13:33 UTC, KimMcAlpine commented on katsdpcal/pipelineprocs.py
> +            parameters[key] = [channel_freqs[bchan].to(u.MHz).value]
Done

2021-07-08 13:34 UTC, KimMcAlpine commented on katsdpcal/pipelineprocs.py
>      channel_freqs : :class:`np.ndarray`
Done

2021-07-08 13:34 UTC, KimMcAlpine commented on katsdpcal/pipelineprocs.py
> +                       " than the default (%.3f MHz)", actual_sol_bandwidth.value,
I know :(,

2021-07-08 13:36 UTC, KimMcAlpine commented on katsdpcal/pipelineprocs.py
> +                bfreq_hz = parameters[freq] * 1e6 * u.Hz
Thats a cool tip

2021-07-08 13:42 UTC, KimMcAlpine commented on katsdpcal/test/test_pipelineprocs.py
> +        self.assertEqual(self.freqs[10092].to(u.MHz).value, parameters['k_bfreq'])
Done

2021-07-08 13:56 UTC, KimMcAlpine commented on katsdpcal/pipelineprocs.py
> +                                   if min(channel_freqs).to(u.MHz).value >= s_freq])
Done

2021-07-08 13:56 UTC, KimMcAlpine commented on katsdpcal/pipelineprocs.py
> +    default_chan_count = min(6400, max_chans_per_server)
Fair enough, that is a better name :). Done

2021-07-08 14:32 UTC, ludwigschwardt approved these changes
Yay!

Astropy units are like those chips: once you pop you can't stop 😄  It will probably now infest the rest of katsdpcal like it did in katpoint 🤣

2021-07-21 10:11 UTC, merged