Update weights
ska-sa/katsdpcal pull request #55
Opened 2021-08-10 14:00 UTC by KimMcAlpine

2021-08-11 09:38 UTC, ludwigschwardt requested changes
Besides pre-apply, does the usual apply also need to update weights? This [comment](https://github.com/ska-sa/katsdpcal/blob/1d9fac3b7e9bf0233940e85bc06b555a25b79622/katsdpcal/scan.py#L771) hints at it :-D

2021-08-11 09:38 UTC, ludwigschwardt commented on katsdpcal/scan.py
>          chan_slice = np.s_[:, bchan:echan, :, :]
Shouldn't you have `modweights` somewhere below (e.g. instead of `corr.tf.cross_pol.weights`)?

2021-08-11 13:04 UTC, KimMcAlpine commented
> Besides pre-apply, does the usual apply also need to update weights? This [comment](https://github.com/ska-sa/katsdpcal/blob/1d9fac3b7e9bf0233940e85bc06b555a25b79622/katsdpcal/scan.py#L771) hints at it :-D

I don't think the usual `apply` needs to update the weights. I think in some far distant past there was an idea that the L1 / corrected visibilities would be streamed to somewhere useful for later use, in this case it would make sense to also update the weights. However we now use katdal for generating the L1 product and in our current model there are only two uses for the usual `apply` ( i.e not a pre-apply step in a solver)
1.) To apply the calibration solutions before flagging, I don't think the weights are considered by the flagger so it won't make any difference if you don't update the weights here   
2.) To make summary scans of the calibrated data to plot in the report. Mostly you are just plotting the visiblities here, but some of these scans are combined in weighted average at the end so this might make a small difference but I suspect the effect is fairly minor. I'll look into this a bit

2021-08-11 13:20 UTC, KimMcAlpine commented on katsdpcal/scan.py
> +            return vis * correction, weights / np.abs(correction)**2
Good point, done

2021-08-11 13:45 UTC, KimMcAlpine commented on katsdpcal/scan.py
> +        if relative:
Good point, done

2021-08-11 13:51 UTC, KimMcAlpine commented on katsdpcal/scan.py
> +            cal_soln = CalSolutions('G', g_soln / g_soln[0], ave_times, soltarget=self.target.name)
I thought it would be a bit odd to have the snr for the relative solutions as the snr can really only be derived from the 'non-relative' solutions as it requires that the phases are rotated to zero.  However I suppose there is nothing stopping you from using the non-relative solutions to derive the snr. Its probably not very important either way because the pipeline never calculates snr for the `pre-g` solutions.

2021-08-11 14:39 UTC, KimMcAlpine commented on katsdpcal/scan.py
>          chan_slice = np.s_[:, bchan:echan, :, :]
yes, you're right. I've fixed this.

2021-08-12 15:49 UTC, ludwigschwardt approved these changes

2021-08-16 08:37 UTC, merged