Modified Reference Antenna Selection and unit tests
ska-sa/katsdpcal pull request #65
Opened 2024-06-14 08:19 UTC by tamerakassie

This PR contains the modified selection of reference antenna as per the initial investigation done in [SPR1-1964](https://skaafrica.atlassian.net/browse/SPR1-1964)
A `select_med_deviation_pnr_ants`  function has been added to calculate the median deviation of antenna peak-to-noise (PNR) values, this function returns a boolean array of antenna values that have a relatively good PNR, i.e one deviation below the median. The `best_refant`, which is the function that calculates the PNR across antennas, has been modified to call the `select_med_deviation_pnr_ants`and thereafter return the corresponding longest baseline solutions for the reference antenna selection.

The `test_calprocs.py` contains the corresponding unit tests for the new solution.

2024-06-21 11:38 UTC, KimMcAlpine requested changes
If any of the comments need more explanation feel free to chat to me.

2024-06-21 11:38 UTC, KimMcAlpine commented on katsdpcal/test/test_calprocs.py
> +        self.array_med_pnr = np.array([1., np.nan, 3, 4, 5])
I don't think that its necessary to make something an attribute inside the test function (ie using `self.array_med_pnr` instead of just plain `array_med_pnr`) unless you plan to reuse this attribute somewhere else in the test class. If you aren't going to reuse this array its simpler to just make it an ordinary variable and it will be easier to read as well.  Also you probably could just call it `med_pnr` as its self evidently an array and shorter names are easier to remember.

2024-06-21 11:38 UTC, KimMcAlpine commented on katsdpcal/test/test_calprocs.py
> +        self.data = np.ones((10, 2, 10), np.complex64)
I don't think you need to explicitly make that data array here as when you multiply out the delays into their complex visibilities you can create an array with the correct shape and data type, so there is no advantage to doing this step here.

2024-06-21 11:38 UTC, KimMcAlpine commented on katsdpcal/test/test_calprocs.py
> +        self.freqs = np.arange(len(self.chans)) / self.chans * self.bandwidth + self.bandwidth
I don't think you need to create the frequency array in such a complicated fashion. In the `make_vis` function in the `test_control` module its useful to use the explicit bandwidths and channels etc because these variables are reused by other functions in the test class, but here we just need an array with some appropriate frequency characteristics. So you can simply go e.g. `freqs = np.linspace(856e6, 890e6, 10)`  without the intermediate bandwidth etc steps. 
Another point here is that you want to choose a frequency range and delay value that will actually make a measurable slope in your visibility data, because that is what our real visibility data looks like. In this instance the difference between channel 0 and channel 10 is too small to produce a visible slope. Consider that `2 * np.pi * delay * frequency ` is the equation relating the angle (in radians) of the visibility measurement to frequency. So if you have a delay of say 20e-12s  (in the range of delays you have supplied)  then you will need a change of 20e12 Hz in frequency to move the angle by 2 pi radians (360 degrees). So the try to select a combination of these two values (delay and frequency) that will give you between 10's to a few 100's of degrees in angle change across the frequency axis.

2024-06-21 11:38 UTC, KimMcAlpine commented on katsdpcal/test/test_calprocs.py
> +        self.flux_array = np.array([self.flux])[:, np.newaxis]
You don't need the flux to test the refant code, it only depends on the angle. In any case you never use these variables that you created here, so you can just remove them.

2024-06-21 11:38 UTC, KimMcAlpine commented on katsdpcal/test/test_calprocs.py
> +        self.offset = np.pi/4
I don't think you need this offset, its not really adding anything to the test so I would get rid of this.

2024-06-21 11:38 UTC, KimMcAlpine commented on katsdpcal/test/test_calprocs.py
> +            baseline_delays[(a1, a2)] = self.delays['polv'][0][a1] - self.delays['polh'][1][a2]
Here you want to create an array with two polarisation axes corresponding to (ant1 'h' - ant2 'h') and (ant1 'v' - ant2 'v') not one polarisation axis corresponding to (ant1 'h' -ant2 'v') as you have here. The `best_refant` function works on the parallel hand visibilities.

2024-06-21 11:38 UTC, KimMcAlpine commented on katsdpcal/test/test_calprocs.py
> +        self.delay_array = np.array([baseline_delays[(ant1, ant2)] for (ant1, ant2) in self.bls])
I think you can achieve what you need to more simply with 
```
k_ant= self.rs.uniform(-50e-12, 50e-12, (2, 5))
delay_bls =  k[:,bls[:,0]] - k[:,bls[:,1]]
```
This will create a (2, 10) array with the correct broadcasting of the two different polarisation delays.

2024-06-21 11:38 UTC, KimMcAlpine commented on katsdpcal/test/test_calprocs.py
> +        self.data[:, 0, :] *= np.angle(self.vis_delay_offset)
This is not doing what you need it to do. By taking `np.angle` you are turning the array into a real valued array (not a complex valued one) and making the magnitudes of `self.data` be equal to the values of the angle of the visibilities. You don't need this line at all, just using the correct version of `vis_delay_offset` should give you what you need.

2024-07-08 09:42 UTC, tamerakassie reviewed
Review for changes made on the initial commit to `calprocs.py` and `test_calprocs.py`

2024-07-08 15:08 UTC, KimMcAlpine approved these changes

2024-07-08 15:08 UTC, KimMcAlpine commented on katsdpcal/test/test_calprocs.py
> +        self.vis = np.array(phase, dtype=complex)
I don't think you need this line, its already a complex array, so you can just rename the previous array as `vis`

2024-07-16 13:19 UTC, tamerakassie commented on katsdpcal/test/test_control.py
> +                           expected_BCROSS_DIODE_rtol=1e-2):
`expected_BCROSS_DIODE_rtol=1e-3)` is correct as in master, retested with the master value and the code passes, omit this change

2024-07-16 13:23 UTC, tamerakassie commented on katsdpcal/test/test_control.py
> +        print(f'BG, {np.abs(BG)}')
omit printing debug

2024-07-16 13:26 UTC, tamerakassie commented on katsdpcal/pipelineprocs.py
> +        except (KeyError):
Flake8 error in my branch that i had to fix, not sure if without the change if it passes on Jenkins

2024-08-08 18:50 UTC, ludwigschwardt requested changes
Another heads-up: Tasmiyah and I are moving all `calprocs` functionality to its own package: https://github.com/ska-sa/katsdpcalproc. You caught me just as I wanted to delete calprocs, but now I'll wait for your PR 😁  Once this is merged, we should move those changes across to the new package as well before removing `calprocs`.

2024-08-08 18:50 UTC, ludwigschwardt commented on katsdpcal/calprocs.py
> +    mad = scipy.stats.median_abs_deviation(med_pnr_ants, nan_policy='omit')
Very nice that you found this! 😊

If you stumble upon a useful function in an external library, it's good to stop and consider a few things:
- How new is this function?
- Does this introduce a new dependency?
- Will it affect my package's existing dependencies?

Since `katsdpcal` already uses `scipy`, there's no new dependency to think about. The function is relatively new though, which is why it hasn't been used up to now 😅

Have a look at the scipy docs:
<img width="928" alt="Screenshot 2024-08-08 at 20 06 15" src="https://github.com/user-attachments/assets/3293c41d-1dbe-42aa-8ce0-7c5aecef5569">
and then at https://pypi.org/project/scipy/#history:
<img width="676" alt="Screenshot 2024-08-08 at 20 17 55" src="https://github.com/user-attachments/assets/7e2b2d49-6e46-48e6-a033-e360194f0666">

It's from scipy 1.5.0 in 2020, which seems old, but `katsdpcal` (mostly from 2017-2019) still accepts `scipy >= 0.17` in `setup.py`... And scipy 1.5.0 needs Python 3.6, which is newer than the 3.5 specified by katsdpcal.

You have a few options here:
- Quietly bump the Python to 3.6 and scipy to 1.5.0 in setup.py, but ideally we want to run `pyupgrade --py36-plus` to get more benefits.
- Go all out and bump it to Python 3.8 (my latest test PR #67 requires it already).
- Don't use this function and consider the existing functionality in `katsdpsigproc` (NoiseEstMADHost) or just write your own. It's already implemented in `katsdpcal.plotting.amp_range`, for example.

It's also a good idea to multiply the MAD by 1.4826 to convert it into a "normal" standard deviation.

2024-08-08 18:50 UTC, ludwigschwardt commented on katsdpcal/test/test_calprocs.py
> +    """Tests for :func:`katsdpcal.calprocs.interpolate_soln"""
You accidentally deleted a backtick here (needed for Sphinx doc reference).

2024-08-08 18:50 UTC, ludwigschwardt commented on katsdpcal/test/test_calprocs.py
> +    """Tests for :func:`katsdpcal.calprocs.select_med_deviation
You accidentally deleted a backtick here (needed for Sphinx doc reference).

2024-08-08 18:50 UTC, ludwigschwardt commented on katsdpcal/test/test_calprocs.py
> +    """Tests for :func:`katsdpcal.calprocs.best_refant"""
You accidentally deleted a backtick here (needed for Sphinx doc reference).

2024-08-08 18:50 UTC, ludwigschwardt commented on katsdpcal/test/test_control.py
> +        self.master_queue = master_queue
This is unnecessary since the `super()` above already does it (`master_queue` lives in the `control.Task` base class).

2024-08-08 18:50 UTC, ludwigschwardt commented on katsdpcal/test/test_control.py
> +        module = multiprocessing
I wonder why you did this... Did you try to run this with `pytest` by any chance? The tests work as expected for me without this. I know it looks strange, being a Merry construct and all, because I also had to figure this out just this week 😂 

The `module` attribute is set by the actual (derived) test classes below: `TestTaskMultiprocessing` and `TestTaskDummy`. As the name implies, this class is just the base for these tests containing common functionality. The `module` attribute is not common and will be set differently for each set of tests. By hardwiring `multiprocessing` here, you are dropping the `TestTaskDummy` checks.

2024-08-09 00:26 UTC, tamerakassie commented on katsdpcal/test/test_control.py
> +        module = multiprocessing
I ran locally with `pytest` that needed this change, and had neglected to change to back when i ran `test_control.py` with `nosetests` thanks for the spot.

2024-08-09 00:35 UTC, tamerakassie commented on katsdpcal/scan.py
> +        print(f'modvis:{modvis}')
This was a debugging statement, missed omitting it in cleanup.

2024-08-12 09:56 UTC, ludwigschwardt commented on katsdpcal/calprocs.py
> +    mad = scipy.stats.median_abs_deviation(med_pnr_ants, nan_policy='omit')
You can always leave a comment in the code that the scipy function could be used once we upgrade to Python 3.6+ in case we forget.

2024-08-12 10:01 UTC, ludwigschwardt commented
I suggest that we squash the branch to a single commit when we eventually merge this. That will avoid committing code that just adds lines and then deletes it again.

2024-08-19 15:17 UTC, tamerakassie commented
I had to do a force-push, after my squashing off commits and resolving conflicts with the base branch. The force push was required because I git pulled origin and resolved conflicts, but it still refused to push.

2024-08-19 15:40 UTC, ludwigschwardt requested changes
I'm not sure what happened here... Your squashing seems to have undone some of your changes.

When I said "squash merge" I meant that when we merge the PR, there is an option to squash all the commits to a single one... 😅  I would not do that before the time, and force-push can be quite destructive unless you are sure about it.

At this point, I wonder if it's not better to make a fresh branch off master, add your changes and make a new PR. Sorry, but there are some really weird stuff in the diff now. 😅

2024-08-19 15:40 UTC, ludwigschwardt commented on katsdpcal/calprocs.py
> +    mad_threshold = median - mad
Your docstring says "above one median deviation of the antenna median PNR". Should this not be `median + mad`?

2024-08-19 15:40 UTC, ludwigschwardt commented on katsdpcal/calprocs.py
> +    ant_longest_bls = np.sort(high_ants)[::-1]
I don't quite get why you are sorting antenna indices (like `[0, 1, 45, 23]`) and then calling it `ant_longest_bls`. Do you mean that the higher antenna indices are generally further from the core than the lower indices?

2024-08-19 15:40 UTC, ludwigschwardt commented on katsdpcal/calprocs.py
> +        Array of indices of antennas in decreasing order of baselength
The term "baselength" and the abbreviation "bls" can be misleading because it makes me think of baseline length. Do you mean distance from the array centre in some sense? It's an approximation if you look at antenna numbers to achieve this. I would just call this an array of antenna indices sorted from "best" to "worse" in terms of how suitable it is as a reference antenna, and then describe the approach in more detail in the main description of the function.

2024-08-19 15:40 UTC, ludwigschwardt commented on katsdpcal/scan.py
> +        print(f'fit_vis: {fitvis.compute()}')
You still have prints here...

2024-08-19 15:40 UTC, ludwigschwardt commented on katsdpcal/scan.py
> +        """if refant_order:
This code is commented out...

2024-08-19 15:40 UTC, ludwigschwardt commented on katsdpcal/test/test_control.py
> +        print(f'ret, {np.abs(ret_BG_interp)}')
More prints...

2024-08-19 15:40 UTC, ludwigschwardt commented on katsdpcal/test/test_control.py
> +        self.master_queue = master_queue
It looks like a lot of these resolved changes have become unresolved somehow...

2024-08-19 15:40 UTC, ludwigschwardt commented on katsdpcal/test/test_control.py
> +                                       ret_KCROSS_DIODE, rtol=1e-1)
Why these changes?

2024-08-19 15:40 UTC, ludwigschwardt commented on katsdpcal/test/test_control.py
> +        heaps = self.prepare_vis_heaps(n_times, rs, ts, vis, flags, weights, weights_channel)
Whoops, something's gone wrong... This doesn't exist anymore.

2024-08-19 15:40 UTC, ludwigschwardt commented on katsdpcal/test/test_control.py
> +        rs = np.random.RandomState(seed=1)
Why are you adding stuff to `test_reset_solution_stores`? Should this not be `test_best_refant`?

2024-08-19 15:46 UTC, tamerakassie commented
I thinks its better to redo my changes in a new branch, this is also becoming confusing for me now.

2024-08-20 07:41 UTC, ludwigschwardt commented
You've committed some random files such as `katsdpcal/FETCH_HEAD` and `katsdpcal/test/dask-worker-space/purge.lock`. Did you run something like `git add .`?

I strongly suggest the following:

Remake your new `SPR1-1964-select-refant` branch off master. It's currently still poisoned by all the dodgy commits. Then add the one good commit.

```
git branch -m SPR1-1964-select-refant SPR1-1964-select-refant-old
git checkout master
git switch -c SPR1-1964-select-refant
git cherry-pick 7766c6b
```
If there are conflicts, fix it at this stage. Then you should have a single good commit with only your intended changes for a new PR.

2024-09-03 23:34 UTC, closed without merging

2024-09-03 23:34 UTC, ludwigschwardt commented
Replaced by #69.