Spr1 3025 integrate ref pointing with cal
ska-sa/katsdpcal pull request #72
Opened 2024-09-17 11:47 UTC by Tasmiyah27

Changes in reduction.py: Added get_offsets function which calculated (x,y) co-ordinates for each pointing, Also added flush_pipeline which is a secondary pipeline calibration that saves beams to telstate.
Changes in control.py: added new solution store  B_pointing.
Changes in test_control.py: added async test function 'test_reference_pointing_capture' which tests the mechanics of the reference pointing feature, ensuring that it is triggered and runs through full course down to asserting shapes and dtypes of expected cal_product in telstate

2024-09-17 14:38 UTC, ludwigschwardt requested changes
A smattering of small changes, but before you add too many more commits, fix these and then please reword the commit message of your first commit...

It currently reads:
```
added test_reference_pointing_capture
```
This is all anyone would see if they wanted to find out in future why you added major functionality in `get_offsets()` and `flush_pipeline()` 😅

You can fix it like this in your local branch (assuming you haven't added any more commits):
```
git rebase -i HEAD~5
```
Then in the editor that pops up, you'll see:
```
pick bee25c3 added test_reference_pointing_capture
pick 75f0c22 flake8 corrections
pick 467ef3e changed self.telstate_cb to telstate_cb
pick aaf91c2 removed print statements
pick 59b193a added pointingcal check in pipeline
```
Edit that to read the following instead, and save and exit the editor:
```
reword bee25c3 added test_reference_pointing_capture
pick 75f0c22 flake8 corrections
pick 467ef3e changed self.telstate_cb to telstate_cb
pick aaf91c2 removed print statements
pick 59b193a added pointingcal check in pipeline
```
This will open yet another editor to change your message. Think about all the stuff you added and try to give an overview of all that, as well as some rationale for adding it.

Afterwards, use a force push to get it back onto GitHub:
```
git push -f
```

2024-09-17 14:38 UTC, ludwigschwardt commented on katsdpcal/control.py
> +            'B_POINTING': solutions.CalSolutionStore('B')
By adding a comma after each item, you avoid changes to the previous last line (i.e. the one with `G_FLUX`) just to add a comma there. In Python `[1, 2, 3,]` is the same as `[1, 2, 3]`.
```suggestion
            'B_POINTING': solutions.CalSolutionStore('B'),
```

2024-09-17 14:38 UTC, ludwigschwardt commented on katsdpcal/pipelineprocs.py
> +        'SNR_EPOINT': 'product_SNR_EPOINT{}'.format(server_id)
Ditto.
```suggestion
        'SNR_EPOINT': 'product_SNR_EPOINT{}'.format(server_id),
```

2024-09-17 14:38 UTC, ludwigschwardt commented on katsdpcal/reduction.py
> +    """Calculate offset co-odinates relative to target for each pointing.
```suggestion
    """Calculate offset co-ordinates relative to target for each pointing.
```

2024-09-17 14:38 UTC, ludwigschwardt commented on katsdpcal/reduction.py
> +    rc=katpoint.RefractionCorrection()
Flake8...
```suggestion
    rc = katpoint.RefractionCorrection()
```

2024-09-17 14:38 UTC, ludwigschwardt commented on katsdpcal/reduction.py
> +def flush_pipeline(ts, parameters, solution_stores, num_chunks=16):
I would not put `num_chunks` as a separate argument in `flush_pipeline`, which is supposed to be a generic function. It should enter the function via `parameters` instead. If we are going to do that later, rather hard-code `num_chunks = 16` inside the function itself, with `# TODO` comment that it should go into the `parameters`.

2024-09-17 14:38 UTC, ludwigschwardt commented on katsdpcal/reduction.py
> +        # Get offset az/el co-ordiantes (direction in which reference antenna is pointing)
```suggestion
        # Get offset az/el co-ordinates (direction in which reference antenna is pointing)
```

2024-09-18 15:16 UTC, ludwigschwardt commented
Hi @Tasmiyah27, do you have more updates for me to review?

2024-09-18 22:46 UTC, Tasmiyah27 commented on katsdpcal/reduction.py
> +def flush_pipeline(ts, parameters, solution_stores, num_chunks=16):
Done

2024-09-19 10:14 UTC, ludwigschwardt commented on katsdpcal/reduction.py
> +    Returns
The function doesn't return anything, technically. The beam solutions are called *side effects*, not return values. Rather just mention it in the main description area below the title and above the "Parameters" section.

2024-09-19 10:17 UTC, ludwigschwardt commented on katsdpcal/reduction.py
> +    """Secondary pipeline calibration.
This is not very descriptive. Let's try another version:
```suggestion
    """Complete any unfinished calibration products remaining in the pipeline.
```

2024-09-19 10:25 UTC, ludwigschwardt commented on katsdpcal/reduction.py
> +    b_solutions = solution_stores['B_POINTING'].get_range(start_time=0, end_time = time.time()).values
There are some type issues here...

`solution_stores['B_POINTING']` is a `CalSolutionStore`.
`solution_stores['B_POINTING'].get_range` returns a `CalSolutions`.
Therefore `b_solutions` will be `CalSolutions.values` which is an array.
You probably wanted it to be a `CalSolutions`.

2024-09-19 10:26 UTC, ludwigschwardt commented on katsdpcal/reduction.py
> +    mid_times = b_solutions.get_range(start_time = 0, end_time= time.time()).times
Here the wheel comes off... 🙂 This should just have been `b_solutions.times`. As it is now, an array doesn't even have a `get_range` method and this probably crashes the pipeline.

2024-09-19 10:31 UTC, ludwigschwardt commented on katsdpcal/reduction.py
> +    target_str = ts.get_range('cbf_target', et = mid_times[-1])[0][0]
The usual pipeline has:
```Python
        t0 = data['times'][scan_slice.start]
        t1 = data['times'][scan_slice.stop - 1]
        n_times = scan_slice.stop - scan_slice.start

        #  target string contains: 'target name, tags, RA, DEC'
        target_str = ts.get_range('cbf_target', et=t0)[0][0]
        target = katpoint.Target(target_str)
```
We therefore want the target just before the start of the scan (`t0` above), so a better approach would be:
```suggestion
    target_str = ts.get_range('cbf_target', et = mid_times[0])[0][0]
```
There really should be only a single target for the entire set of solutions but we currently don't doublecheck that.

2024-09-19 10:32 UTC, ludwigschwardt commented on katsdpcal/reduction.py
> +    pres = ts.get_range('anc_air_pressure', et = mid_times[-1])[0][0]
This ideally needs katdal sensor framework for interpolation (note for future work).

2024-09-19 10:32 UTC, ludwigschwardt commented on katsdpcal/reduction.py
> +        az = ts.get_range(str(refant.name)+'_pos_actual_scan_azim', et=j )
This ideally needs katdal sensor framework for interpolation (note for future work).

2024-09-19 10:34 UTC, ludwigschwardt commented on katsdpcal/reduction.py
> +    offsets = get_offsets(ts, b_solutions, target, mid_times, temp, pres, humi, parameters)
This is wrong... b_solutions should not be there (another pipeline crash).
```suggestion
    offsets = get_offsets(ts, parameters, target, mid_times, temp, pres, humi)
```

2024-09-19 10:36 UTC, ludwigschwardt commented on katsdpcal/reduction.py
> +    data_points = pointing.get_offset_gains(b_solutions, offsets, ants, dump_period,
Doublecheck your parameter lists...
```suggestion
    data_points = pointing.get_offset_gains(b_solutions, offsets, ants,
```

2024-09-19 10:46 UTC, ludwigschwardt commented on katsdpcal/reduction.py
> +    beams = pointing.beam_fit(data_points, ants, num_chunks, beam_center=(0.5, 0.5))
Not sure how the beam center came to be initialised to (0.5, 0.5) instead of the obvious (0.0, 0.0)... I've fixed this in katsdpcalproc as well.
```suggestion
    beams = pointing.beam_fit(data_points, ants, num_chunks)
```

2024-09-19 10:47 UTC, ludwigschwardt commented on katsdpcal/reduction.py
> +    beam_sol = np.full((num_chunks, len(pols), len(ants), 5), np.nan)
The default dtype will be float64 and we want float32...
```suggestion
    beam_sol = np.full((num_chunks, len(pols), len(ants), 5), np.nan, dtype=np.float32)
```

2024-09-19 10:48 UTC, ludwigschwardt commented on katsdpcal/reduction.py
> +    beam_sol_SNR = np.full((num_chunks, len(pols), len(ants), 5), np.nan)
Ditto.
```suggestion
    beam_sol_SNR = np.full((num_chunks, len(pols), len(ants), 5), np.nan, dtype=np.float32)
```

2024-09-19 10:48 UTC, ludwigschwardt commented on katsdpcal/reduction.py
> +                beam_sol_SNR[c,:,a]=1/np.r_[chunk.center, chunk.width, chunk.height]
These should be the `std_` versions of the parameters...

2024-09-19 10:50 UTC, ludwigschwardt commented on katsdpcal/reduction.py
> +            else:
I would rather just add the lines:
```Python
if chunk.is_valid:
    beam_sol_SNR[c, :, a, 4] = 0.0
```
instead of the whole reassignment. I've suggested a zero value on the SNR of the height instead of a NaN value on the height itself as it is less destructive.

2024-09-19 10:51 UTC, ludwigschwardt commented on katsdpcal/reduction.py
> +        for c,chunk in enumerate(beams[ant]):
Call it `beam` instead of `chunk`. That seems more fitting (pardon the pun!).

2024-09-19 10:52 UTC, ludwigschwardt commented on katsdpcal/reduction.py
> +    beam_sol=solutions.CalSolution(soltype='P', soltime=soltime, solvalues=beam_sol, soltarget=target.name)
Rather use the `solsnr` parameter of this `CalSolution` to store the SNR instead of a separate `CalSolution`.

2024-09-19 10:53 UTC, ludwigschwardt commented on katsdpcal/reduction.py
> +    save_solution(ts, parameters['product_names']['product_SNR_EPOINT'], None, beam_sol_SNR)
The `SNR_` part is taken care of internally in `save_solution` (I think/hope).

2024-09-19 12:21 UTC, Tasmiyah27 commented on katsdpcal/reduction.py
> +    b_solutions = solution_stores['B_POINTING'].get_range(start_time=0, end_time = time.time()).values
so I should remove the .values?

2024-09-19 12:31 UTC, Tasmiyah27 commented on katsdpcal/reduction.py
> +    pres = ts.get_range('anc_air_pressure', et = mid_times[-1])[0][0]
are you referring  to the atmospheric conditions or the target or both?

2024-09-19 12:57 UTC, KimMcAlpine requested changes

2024-09-19 12:57 UTC, KimMcAlpine commented on katsdpcal/reduction.py
> +    for a, ant in enumerate(ts.cal_antlist):
Why not just use `ants` here instead of `ts.cal_antlist` as that is what you used further up in the function ? It will be more consistent.

2024-09-19 12:57 UTC, KimMcAlpine commented on katsdpcal/test/test_control.py
> +            for i in range(0,n_pointing):
Is the number pointings related to the number of samples you need per dump ? I wouldn't have thought so, but I wouldn't use this variable here unless it is specifically related, because what happens if you decide to change the number of pointings in the future for some reason.

2024-09-19 12:57 UTC, KimMcAlpine commented on katsdpcal/reduction.py
> +    """Secondary pipeline calibration.
I would consider adding a brief description here highlighting the purpose of this secondary pipeline. Otherwise its a bit unclear why you need it. It can be brief with a mention of your ticket for further details. Something along the lines of "Collect pipeline beam solutions generated on previous target tracks and use these to solve for pointing offsets"

2024-09-19 13:09 UTC, Tasmiyah27 commented on katsdpcal/reduction.py
> +                beam_sol_SNR[c,:,a]=1/np.r_[chunk.center, chunk.width, chunk.height]
does this only apply to the SNR?

2024-09-19 13:10 UTC, Tasmiyah27 commented on katsdpcal/reduction.py
> +            else:
You mean if it is not valid?

2024-09-19 13:25 UTC, Tasmiyah27 commented
Will do @KimMcAlpine comments in the next round of commits, @ludwigschwardt I've added some questions under some of your previous comments for clarification, hopefully I made the correct changes

2024-09-19 13:51 UTC, ludwigschwardt commented on katsdpcal/reduction.py
> +    pres = ts.get_range('anc_air_pressure', et = mid_times[-1])[0][0]
Instead of `ts.get_range` we need something that does linear interpolation. This currently picks the last sample before the end time `et`, but it could be way in the past...

2024-09-19 13:55 UTC, ludwigschwardt commented on katsdpcal/reduction.py
> +            else:
Doh, yes! 😁

2024-09-19 15:24 UTC, ludwigschwardt requested changes
Changes to the main code for now (one of them a critical bug).

2024-09-19 16:52 UTC, ludwigschwardt requested changes
Some more breaking stuff fixed here :-)

2024-09-19 16:52 UTC, ludwigschwardt commented on katsdpcal/test/test_control.py
> +        n_times = n_track + n_await
```suggestion
        n_times = n_track + n_slew + n_await
```

2024-09-19 16:52 UTC, ludwigschwardt commented on katsdpcal/test/test_control.py
> +        max_extent = 1
Rather indicate that it's a float.
```suggestion
        max_extent = 1.0
```

2024-09-19 16:52 UTC, ludwigschwardt commented on katsdpcal/test/test_control.py
> +                azel = [katpoint.wrap_angle(azel[0]), katpoint.wrap_angle(azel[1])]
Only azimuth needs `wrap_angle`, as we can't go over the top or below ground in elevation :-)

Also, more importantly, katpoint always returns radians, while the sensors are in degrees.

2024-09-19 16:52 UTC, ludwigschwardt commented on katsdpcal/test/test_control.py
> +                self.telstate.add(str(ant_objects[0].name)+'_pos_actual_scan_azim', azel[0], ts=ts)
No need for str.

2024-09-19 16:52 UTC, ludwigschwardt commented on katsdpcal/test/test_control.py
> +            for i in range(0,n_pointing):
Agreed. You really want
```Python
for i in range(8 * (n_track + n_slew) / n_pointing)
```
here, because you need three dumps per offset, sampled 8 times per SDP dump. You could make that explicit by setting `pos_sensor_period = 0.5`, then the "8" is really `self.dump_period / pos_sensor_period`. And notice that you don't need to say `range(0, 10)`... You can just say `range(10)`.

2024-09-19 16:52 UTC, ludwigschwardt commented on katsdpcal/test/test_control.py
> +        ts = start_time
You probably also need a loop over antennas *before* setting `ts`.
```suggestion
        for ant in ant_objects:
            ts = start_time
```

2024-09-19 16:52 UTC, ludwigschwardt commented on katsdpcal/test/test_control.py
> +                                            antenna=ant_objects[0], timestamp=ts)
All these `ant_objects[0]` will then become `ant`.

2024-09-19 16:52 UTC, ludwigschwardt commented on katsdpcal/test/test_control.py
> +                assert EPOINTn.dtype == np.float64
```suggestion
                assert EPOINTn.dtype == np.float32
```

2024-09-19 17:07 UTC, ludwigschwardt requested changes
This why there's no `product_EPOINT0`...

2024-09-19 17:07 UTC, ludwigschwardt commented on katsdpcal/reduction.py
> +    save_solution(ts, parameters['product_names']['product_EPOINT'], None, beam_sol)
Found it! 😁 
```suggestion
    save_solution(ts, parameters['product_names']['EPOINT'], None, beam_sol)
```

2024-09-19 18:25 UTC, ludwigschwardt requested changes
Now it will hopefully run! 🤞🏾

2024-09-19 18:25 UTC, ludwigschwardt commented on katsdpcal/reduction.py
> +    data_points = pointing.get_offset_gains(b_solutions.values(), offsets, ants, channel_freqs,
It's not a function, just an attribute...
```suggestion
    data_points = pointing.get_offset_gains(b_solutions.values, offsets, ants, channel_freqs,
```

2024-09-19 18:25 UTC, ludwigschwardt commented on katsdpcal/reduction.py
> +            if beam.is_valid:
Here is my suggestion:
```Python
            beam_sol[c, :, a] = np.r_[beam.center, beam.width, beam.height]
            beam_sol_SNR[c, :, a] = 1 / np.r_[beam.std_center, beam.std_width, beam.std_height]
            if not beam.is_valid:
                beam_sol_SNR[c, :, a, 4] = 0.0
```
It is only necessary to set the height uncertainty when the beam is invalid. The rest has to happen regardless.

2024-09-19 18:25 UTC, ludwigschwardt commented on katsdpcal/test/test_control.py
> +                                                antenna=ant_objects[0], timestamp=ts)
```suggestion
                                                antenna=ant, timestamp=ts)
```

2024-09-19 18:25 UTC, ludwigschwardt commented on katsdpcal/test/test_control.py
> +                    azel = [katpoint.wrap_angle(azel[0]), azel[1]]
```suggestion
                    azel = [katpoint.rad2deg(katpoint.wrap_angle(azel[0])), katpoint.rad2deg(azel[1])]
```

2024-09-19 18:30 UTC, ludwigschwardt requested changes
More fixes highlighted by the latest Jenkins test failure (yay, finally tests that help!).

2024-09-19 18:30 UTC, ludwigschwardt commented on katsdpcal/test/test_control.py
> +        num_pos_updates = self.dump_period / pos_sensor_period
This should be an int.
```suggestion
        num_pos_updates = int(np.round(self.dump_period / pos_sensor_period))
```

2024-09-19 18:30 UTC, ludwigschwardt commented on katsdpcal/test/test_control.py
> +                for i in range(num_pos_updates * (n_track + n_slew) / n_pointing):
The answer should be an int and not a float...
```suggestion
                for i in range(num_pos_updates * (n_track + n_slew) // n_pointing):
```

2024-09-19 23:39 UTC, ludwigschwardt requested changes
A small niggle, but still chasing down the test failure...

2024-09-19 23:39 UTC, ludwigschwardt commented on katsdpcal/reduction.py
> +            beam_sol[c,:,a]=np.r_[beam.center, beam.width, beam.height]
You've deleted too much...
```suggestion
            if beam is None:
                continue
            beam_sol[c, :, a] = np.r_[beam.center, beam.width, beam.height]
```

2024-09-19 23:39 UTC, ludwigschwardt commented on katsdpcal/reduction.py
> +            beam_sol_SNR[c,:,a]=1/np.r_[beam.std_center, beam.std_width, beam.std_height]
Just better Python styling:
```suggestion
            beam_sol_SNR[c, :, a] = 1 / np.r_[beam.std_center, beam.std_width, beam.std_height]
```

2024-09-19 23:39 UTC, ludwigschwardt commented on katsdpcal/reduction.py
> +                beam_sol[c,:,a]=np.r_[beam.center, beam.width, beam.height]
Unnecessary line.
```suggestion
```

2024-09-19 23:39 UTC, ludwigschwardt commented on katsdpcal/reduction.py
> +                beam_sol_SNR[c, :, a, 4] = 0.0
I now prefer `-1` here since then one can associate it with `std_height`, even if you forgot how many parameters there are.
```suggestion
                beam_sol_SNR[c, :, a, -1] = 0.0
```

2024-09-20 05:42 UTC, Tasmiyah27 commented on katsdpcal/reduction.py
> +            beam_sol[c,:,a]=np.r_[beam.center, beam.width, beam.height]
ah sorry that was an accident

2024-09-20 12:12 UTC, ludwigschwardt commented on katsdpcal/reduction.py
> +    for a, ant in enumerate(ts.cal_antlist):
That was a lifesaver, a necessity! :tada:

2024-09-20 12:54 UTC, merged